### PR TITLE
Fix wp dir finding

### PR DESCRIPTION
**Pull request by mAAdhaTTah**
The only issue with this implementation is anyone can pass `d` as a query arg to this url and would be able to execute any arbitrary admin.php file. Is there some check we should perform before including?

### CODE REVIEW

**Comment by AramZS** [comment]
Yeah, that seems like it might be a big security risk. We should think about how to double check that only the file we want to load is loading.

**Comment by mAAdhaTTah** [comment]
We could get a hash of the file and make sure it matches one of the known hashes of that file. That would mean precomputing and maintaining a list of hashes for that file for various WP versions, or precomputing the hash for that file for the current install and saving it someplace known relative to the location of the `nominate-this.php` file.

If we're going to go that route, we could just precompute the location of the `admin.php` file and save that someplace. The problem with both of these solutions is the only thing really "known" at the time the file is loaded is its own location, so we'd have to save this stuff in the plugin directory itself, which I'm not a fan of.

Another idea is, instead of directly loading the file in the browser, leverage WordPress' rewrite rules so we can just server whatever we'd like at an arbitrary url within the context of WordPress, rather than trying to load WP up after we load the file.

**Comment by 3th0** [comment]
Any news about this pull request ? 

During a test of Pressforward in a test environment we're facing somes issues : 

`PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function ot_register_meta_box() in /www/wordpress/wp-content/themes/hueman/functions/init-admin.php:427
Stack trace:
#0 /www/wordpress/wp-includes/class-wp-hook.php(298): hu_custom_meta_boxes('')
#1 /www/wordpress/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array)
#2 /www/wordpress/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#3 /www/wordpress/wp-admin/admin.php(154): do_action('admin_init')
#4 /www/wordpress/wp-content/plugins/pressforward/includes/nomthis/nominate-this.php(37): require_once('/www/...')
#5 {main}
  thrown in /www/wordpress/wp-content/themes/hueman/functions/init-admin.php on line 427" while reading response header from upstream, client: 0.0.0.0, server: HOST.TLD, request: "GET /wp-content/plugins/pressforward/includes/nomthis/nom
`
Seems to fail because Pressforward include wp-admin out of context. Which causes 500's Fatal errors.
nominate-this.php line 37: 
`/** WordPress Administration Bootstrap */
require_once( $wp_bootstrap . '/admin.php');`

When i'm watching the different issues, I think they are all linked to this bad include of wp-admin/admin.php, for example:
Https://github.com/PressForward/pressforward/issues/871
Or others issues with X plugins conflitcts… 

Beyond the ugly include and the more ugly multiples dirname,  we can care seriously about the security risks and/or crashes of this code. For any case It seems that this is not a best practice to do this in wordpress context. For all of theses reasons we can't install PressForward on our paltform. Please consider the pull request of @mAAdhaTTah 

`
global $pagenow;
$wp_bootstrap = dirname(dirname(dirname(dirname(dirname(dirname(__FILE__))))) );
#echo '<pre>'; var_dump($_POST); die();
$wp_bootstrap_d = dirname(dirname(dirname(dirname(dirname(dirname(dirname(__FILE__))))) )); 

if (is_dir($wp_bootstrap.'/wp-admin')){
   $wp_bootstrap = $wp_bootstrap.'/wp-admin';
} elseif (is_dir($wp_bootstrap.'/wordpress/wp-admin')){
   $wp_bootstrap = $wp_bootstrap.'/wordpress/wp-admin';
} elseif (is_dir($wp_bootstrap_d.'/wordpress/wp-admin')) {
        $wp_bootstrap = $wp_bootstrap_d.'/wordpress/wp-admin';
} elseif (is_dir($wp_bootstrap.'/data/current/wp-admin')) {
        $wp_bootstrap = $wp_bootstrap.'/data/current/wp-admin';
} elseif (is_dir($wp_bootstrap.'/blog/wp-admin')) {
        $wp_bootstrap = $wp_bootstrap.'/blog/wp-admin';
} elseif (is_dir($wp_bootstrap_d.'/blog/wp-admin')) {
        $wp_bootstrap = $wp_bootstrap_d.'/blog/wp-admin';
} elseif (is_dir($wp_bootstrap.'/wp/wp-admin')) {
        $wp_bootstrap = $wp_bootstrap.'/wp/wp-admin';
} else {
        echo 'Base directory attempt at: <pre>'; var_dump($wp_bootstrap);
        echo 'Nominate This can not find your WP-Admin directory'; die();
}
`

http://wordpress.stackexchange.com/questions/191678/why-not-to-include-reference-to-wp-admin-admin-php-in-plugin

Our environment : 
PHP binary:	/usr/bin/php7.0
PHP version:	7.0.14-1~dotdeb+8.1
php.ini used:	/etc/php/7.0/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI packages dir:	/root/.wp-cli/packages/
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	1.0.0

+ latest Wordpress (4.7) with all plugins∕themes up to date.

**Comment by mAAdhaTTah** [comment]
As this PR currently stands, it can't be merged, as it's a major security hazard, as it would allow anyone to pass in a path to the bookmarklet and have it executed on the server. @AramZS and I discussed alternate approaches, and we haven't been able to settle on anything.

We were looking for something more robust than the `elseif` blocks you pasted above, but given that WordPress can be installed in an arbitrarily named subdirectory, and the `wp-content` folder can also be arbitrarily named, the combination makes it difficult to come up with a robust solution.

**Comment by AramZS** [comment]
At long last this should now be resolved in the upcoming 4.3.0 release.

**Pull request closed without merging**
