### PR TITLE
Feature/upgrade jaxion

### PR DESCRIPTION
**Pull request by mAAdhaTTah**

### CODE REVIEW

**Comment by AramZS** [comment]
@mAAdhaTTah Can you push a fix for the following issue: the system doesn't switch away from `.min` files when WP_DEBUG is enabled. I'm changing it in 5.1.x, but it should be reflected in your Core.

**Comment by mAAdhaTTah** [comment]
This is intended to be handled in userland; Assets\Register#set_debug is
responsible for whether it serves minified assets or not. I don't think
Jaxion should make assumptions about how you decide to put your plugin in
debug mode.

**Comment by AramZS** [comment]
I disagree, but see your point. Let's split the difference. While un-minified scripts is not necessarily the expectation of WP_DEBUG it is the expectation of SCRIPT_DEBUG (See https://pippinsplugins.com/use-script_debug-enable-non-minified-asset-files/ ). What about including a check for that as a consideration of .min files? Considering this is, in a fundamental way, a breaking change that requires new scripts and style sheets to be built, it would be good to have the check respect a standard debug variable of some type. 

On a longer timeline, it would also be useful to have the option to look in a different folder and not just a different file name.

**Comment by mAAdhaTTah** [comment]
The Assets\Register class has to use something to determine whether it should serve minified assets or not. My default was to leave that decision to the user to decide for themselves how and when. Relying on a constant like `SCRIPT_DEBUG` also makes sense as a potential option. If you think `SCRIPT_DEBUG` makes more sense, we should deprecate `Assets\Register#set_debug` and solely rely on it. It would mean users will be required to provide both `.min.{js,css}` & `.{js,css}` files, but in the vein of "Decisions, Not Options," that may be better.

But an API that "splits the difference", and serves minified assets kinda based on `SCRIPT_DEBUG`, but also kinda on userland implementation, would muddy the API and be confusing to users (which takes precedence? which should I use? should I prefer to rely on the constant or do it myself?). This too many choices, so we should provide one way for you to decide for yourself (`set_debug`) or one way to decide for you (`SCRIPT_DEBUG`).

I'd also be open to changing the default behavior of `Register` and put it in debug mode by default, serving unminified assets, which perhaps would be less surprising, as it's only adding `.min` when you consciously turn it off debug mode by implementing your custom `set_debug` logic.

Thoughts?

**Comment by mAAdhaTTah** [comment]
I opened an issue here to discuss: https://github.com/intraxia/jaxion/issues/20 I'm going to update that later this afternoon with more details of the possible approaches.

**Pull request merged**
