### PR TITLE
Adds post type and post status configuration

### PR DESCRIPTION
**Pull request by douglaslinsmeyer**
- Adds ability to designate post type of new content
- Adds ability to designate post status of new content

### CODE REVIEW

**Comment by douglaslinsmeyer** [comment]
Look forward to feedback.

**Comment by douglaslinsmeyer** [comment]
Any movement on this?

**Comment by AramZS** [comment]
@douglaslinsmeyer Hi! We're entering this into the to do list for release 3.6.x! We'll be reviewing the PR this or next month, I'll get back to you as soon as I do.

**Comment by douglaslinsmeyer** [comment]
Any word on this? I can't update your plugin until it's either been merged or forked/rebased.

**Comment by AramZS** [comment]
Hey @douglaslinsmeyer I'm not sure why it isn't showing here, but I have indeed merged your changes in to 3.6.x, to be released with that version release in the next week or so. 

Your code was great, it did miss an alteration needed to the check process to insure you couldn't dupe publish from the nomination area, other than that, I just moved it into the new templating system we are using for the settings page. Much thanks, this is a great feature! https://github.com/PressForward/pressforward/commit/6dd3e1b140b8782de348230d8aa194ae9667841e

**Comment by douglaslinsmeyer** [comment]
Cool! Thanks man, keep it up - this project is definitely a unique one.

-DL

**Comment by AramZS** [comment]
Thanks! Sorry it took so long, we'd love to see more contributions in the future if you have more ideas!

**Pull request closed without merging**
