### PR TITLE
OPML Classes Unit Tests + Code Review

### PR DESCRIPTION
**Pull request by mAAdhaTTah**

### CODE REVIEW

**Comment by mAAdhaTTah** [comment]
@AramZS This is ready to be merged. There's definitely more that can be done with these 3 files, but I'll open another PR to continue working on it if this needs to be merged ASAP.

**Comment by mAAdhaTTah** [comment]
Note the failing tests are a deprecation notice in PHP5.5 running WP 3.6.1, which still uses the old `mysql` extension. Up to you whether you want to include either 5.5+ or old WP versions in these tests.

**Comment by AramZS** [comment]
Merge confirmed, prepping for move into release branch now.

**Comment by mAAdhaTTah** [comment]
Woot!

**Pull request merged**
